[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[secrets]
  # Omit GITHUB_REPO and GITHUB_BRANCH from secret scanning
  # These are public repository information, not sensitive secrets
  omit_keys = ["GITHUB_REPO", "GITHUB_BRANCH"]
